services:
  php-cli:
    build:
      context: .
      dockerfile: builds/php-cli/Dockerfile
      args:
        - APP_SRC=${APP_SRC}
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${APP_SRC}:/usr/src/app
    command: >
      sh -c "[ -d vendor ] || composer install --no-interaction --optimize-autoloader && php bin/bot.php"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${APP_SRC}/migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: